#!/bin/sh

sudo echo Wi-Fi is rebooting &&
sudo modprobe -r iwlwifi && sleep 10 &&
sudo modprobe iwlwifi &&
sudo echo Wi-Fi established &&
sleep 1 && clear

## This file makes it easier for you,
## just put it go /usr/bin/ enable
## execute as a program and run it in
## terminal and wait for 10 seconds.
